//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportStore.Data
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Products
    {
        public int ProductID { get; set; }
        public string Category { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public SolidColorBrush Background { get; internal set; }
    }
}
